// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daacyzxsurjgbxytsfuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhYWN5enhzdXJqZ2J4eXRzZnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDA5MDcsImV4cCI6MjA3MjM3NjkwN30.InIUbbSJaPcWaZ-g9Yi6az7Ygqt4h_zDulhWwKOU5Pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});